# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10690a2d4f0eae833f21cfdfde0ad581658d88b44078e51e8e8e441021b2979d8b41e04f9629ad211eaecabaa425895d2a7b00ace99b15060b6db8dc9766f406

test:
  secret_key_base: ae76d18d5fdb355ba253a134e20c1f8b1326df95d51a626ac0ae05e3d90888566afa5b994ac2d6d9a433ed6bf04dfc8297b2dd80fdc48403b3fface3d8c2eb76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
